### ISSUE TITLE
src/role/worker_functions.py: get_nodes(bbox, configuration)

### ISSUE THREAD

**Issue by tufftuff93** [geometalab/OSMDeepOD#129]
Hello,

The function get_node gives me errors when len(walker.streets) = 0. 

May be it try to evaluate "configuration.follow_streets" but since configuration changes, shouldn't it be configuration.DETECTION.followstreets ?

The ouput when error
Traceback (most recent call last):
  File "main.py", line 138, in <module>
    main_func()
  File "main.py", line 134, in main_func
    args.func(args, configuration)
  File "main.py", line 21, in manager
    manage.run()
  File "xxxxxxx/OSMDeepOD/OSMDeepOD/src/role/manager.py", line 26, in run
    worker_functions.standalone(bboxes=self.small_bboxes, configuration=self.configuration)
  File "xxxxxxx/OSMDeepOD/OSMDeepOD/src/role/worker_functions.py", line 55, in standalone
    nodes += get_nodes(bbox, configuration)
  File "xxxxxxx/OSMDeepOD/OSMDeepOD/src/role/worker_functions.py", line 21, in get_nodes
    if len(walker.streets) > 0 or not configuration.follow_streets:
AttributeError: 'Configuration' object has no attribute 'follow_streets'

**Comment by Murthy10** [comment]
@tufftuff93 thanks for the issue notification, you are right. 
I fixed it and it's now in the master branch (had this issue with follow_streets more than once)
